//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagementSystem.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Orders()
        {
            this.Tbl_OrderDetails = new HashSet<Tbl_OrderDetails>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    
        public virtual Tbl_Customers Tbl_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderDetails> Tbl_OrderDetails { get; set; }
        public virtual Tbl_OrderStatus Tbl_OrderStatus { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
