//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagementSystem.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Products()
        {
            this.Tbl_OrderDetails = new HashSet<Tbl_OrderDetails>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<decimal> unit_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderDetails> Tbl_OrderDetails { get; set; }
        public virtual Tbl_ProductCategories Tbl_ProductCategories { get; set; }
    }
}
