//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagementSystem.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Statistics
    {
        public int statistic_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string statistic_target { get; set; }
        public Nullable<int> target_id { get; set; }
        public string time_period { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string metric_name { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual Tbl_StatisticTypes Tbl_StatisticTypes { get; set; }
    }
}
